server:
  port: 8888
eureka:
  instance:
    hostname: 192.168.1.203
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
